/* Generated by the NeXT Project Builder 
   NOTE: Do NOT change this file -- Project Builder maintains it.
*/

#import "colManager.h"

void main(int argc, char *argv[]) {

    [colManager sharedApplication];
    if ([NSBundle loadNibNamed:@"modeleNcol.nib" owner:NSApp])
	    [NSApp run];
	    
    [NSApp release];
    exit(0);
}
