
/* Generated by Interface Builder */

#import <AppKit/AppKit.h>
#import <AppKit/psopsOpenStep.h>
#import <streams/streams.h>

@interface XYPlotView:NSView
{
    double xMinValueMemo,xIncValueMemo,xMaxValueMemo;
    double yMinValueMemo,yIncValueMemo,yMaxValueMemo;
    double lineWidthValueMemo, offsetValueMemo;


    id     toolboxPanel;
    id     XYMatrix;
    id     commandsMatrix;
    id     switchesMatrix;
    float	 *initialTabX;
    float	 **initialTabY;
    int 	 initialNbVoies;
    int 	 initialNbPoints;
    int 	 expandMode;

    id     plotParam;
    id     theFontManager;
    id     legendFont;
    id     legendTitleFont;
    id     xTitleFont;
    id     yTitleFont;
    id     mainTitleFont;
    id     ticLabelFont;

    float	borderBoxThickness;
    float	lineThickness;
    float	ticMarkThickness;
    float	gridThickness;
    float	frameBoxThickness;
    float	axisThickness;
    float	symbolSize;
    float errorBarBaseWidth;

    float	ppxunit, ppyunit;	/* pixels per xunit, pixels per y unit */
    float	xlegend[2], **ylegend;	/* for legend drawing (fixed dimension here) */

    int	printColor;
    int	legend;
    int	legendBox;
    int	borderBox;
    int	frameBox;
    int	gridDotted;
    int	axes;
    int	majorTicMarks,minorTicMarks;
    int	drawingLegendLines,drawingLegendSymbols;
    int	legendOpaque,opaqueBackground;
    int	handFormatXaxis,handFormatYaxis;
    int	logoFlag, paperSwitchRow, xLinLogState, yLinLogState;
    int	autoPaperState, autoMaxMinState, borderState, gridState, colorState, styledLines;

    NSRect legendbox;
    NSRect xtitlebox, ytitlebox, maintitlebox;
    NSRect oldbounds;

    char	*xAxisTitle;
    char	*yAxisTitle;
    char	*mainTitle;
    char	*legendTitle;
    char	*curveTitle;

    int	xFormatLeft,xFormatRight,xFormatExponent;
    int	yFormatLeft,yFormatRight,yFormatExponent;

    float	xIncValue,xMinValue,xMaxValue;
    float yIncValue,yMinValue,yMaxValue;
}

- saveAsTiff:sender;
- (void)copyTIFtoPasteBoard;
- (void)toggleExpandMode;
- (void)showToolboxPanel;
- (void)memorizeValues;
- (void)setToMemoValues;
- (void)loadParameters;
- (void)saveParameters;


- initWithFrame:(NSRect)frameRect;
- (void)clear:(id)sender;
- setDrawColor:(float) color;
- drawLines:sender :(BOOL)xaxislog :(BOOL)yaxislog;
- drawTicMarks:(float)xmin :(float)xmax :(float)ymin :(float)ymax;

    /*
     - startPlot;
     - startLegend;
     - drawLegend:sender;
     - drawSymbols:sender :(BOOL)xaxislog :(BOOL)yaxislog;
     - drawErrorBars :(BOOL)xaxislog :(BOOL)yaxislog;
     */

- (id)xymatrix;

- plotFromStream:(NXStream *)dataStream;

- (float *)xdata:(int)n;	/* provide data for drawing the curves */
- (float **)ydata:(int)n;	/* and symbols in the legend box       */
- (int)nPoints:(int)n;		/* provide no. of points to use in legend drawing */
- (int)nCurves:(int)n;
- (int)nFiles;

- (BOOL)has_ebars:(int)n;

- mainTitleFont;
- xTitleFont;
- yTitleFont;
- legendFont;
- legendTitleFont;
- ticLabelFont;


- setMainTitleFont:aFont;
- setXTitleFont:aFont;
- setYTitleFont:aFont;
- setLegendFont:aFont;
- setLegendTitleFont:aFont;
- setTicLabelFont:aFont;
    
// Any subclass of View needs to implement its own drawSelf method
- (void)drawRect:(NSRect)rects;

- saveEPS:sender;
//- savePSCode:(char *)aFile;

- setBorder:(int)state;
- setGrid:(int)state;
- setGridDotted:(int)v;

- setXLinLogState:(int)state;
- setYLinLogState:(int)state;

- setAutoMaxMinState:(int)state;
- setAutoPaperState:(int)state;
- setPaperSwitchRow:(int)state;   // Set the "paper Type" to auto on switch
- setLogoFlag:(int)state;
- (int)logoFlag;

    /*
- setMainTitle:(const char *)aString;
- setXAxisTitle:(const char *)aString;
- setYAxisTitle:(const char *)aString;
- setCurveTitle:(const char *)aString;
- setLegendTitle:(const char *)aString;


- (const char *)mainTitle;
- (const char *)xAxisTitle;
- (const char *)yAxisTitle;
- (const char *)curveTitle;
- (const char *)legendTitle;
    */

- (void)setXIncValue:(float)passedValue;
- (void)setXMinValue:(float)passedValue;
- (void)setXMaxValue:(float)passedValue;
- (void)setYIncValue:(float)passedValue;
- (void)setYMinValue:(float)passedValue;
- (void)setYMaxValue:(float)passedValue;
- (float)xIncValue;
- (float)xMinValue;
- (float)xMaxValue;
- (float)yIncValue;
- (float)yMinValue;
- (float)yMaxValue;

- (void)repositionTitles;
    
// Fabrice Wendling - Aout 2001
- copyPStoPboard;
- setX:(float*)tabX andY:(float **)tabY nbVoies:(int)nbV nbPoints:(int)nbP;
- redrawPlot:sender;
- resetMinMax:sender;
- executeCommand:sender;
- removeXLabels;
- removeYLabels;
- makeStreamAndPlot;
- saveDataAsTxt;

@end